### ISSUE TITLE
Instruction for adding a city

### ISSUE THREAD

**Issue by Inesgor** [unixsheikh/salahtime#1]
Assalaamu Alaikum, Shaykhuna.

I know this is quite an old repo. I wanted to add my own city and recompile it. Would you please add a section to the readme about where the data is from and any instruction for those who don't know C? 
Firstly, there is the `europe_copenhagen.c` file, from which I will create a `<mycontinent>_<mycity>.c`. 
Doing `grep "euro" ./*` showed two instances of `europe_copenhagen` in `salahtime.c`, which are:
  1. `#include "europe_copenhagen.c"`
  2. `display_calendar(europe_copenhagen, add_sub_min);`
So it doesn't seem hard for me to create one for my city, or any city. Is there anything I need to know? I request you to add more info to the readme. 

Also, add information about where do we copy the `salahtime.1` file to, for the manpage, the way you added for `salahtime` binary.  

Jazakum Allahu Khaira.

**Comment by Inesgor** [comment]
Assalaamu Alaikum Sheikh.
I just finished shifting this tool to work for my city. Wasn't hard at all & didn't require knowledge of C. 
Jazak Allahu khaira, for making this. 
I also made some other changes, which might interest you, if at all.

**Comment by unixsheikh** [comment]
Alaikum as-salam wa rahmatulahi wa baraktu

Wa iyak!

You are welcome to make a pull request if you feel like it ;)
